#from .rep_dropout import RepDropoutGPT2LMHeadModel
from .templlm_qwen2_5 import TempLLMQwen2ForCausalLM
from .templlm_llama import TempLLMLlamaForCausalLM
from .templlm_qwen3 import TempLLMQwen3ForCausalLM
from .templlm_qwen3_moe import TempLLMQwen3MoeForCausalLM
# from .templlm_gptoss import TempLLMGptOssForCausalLM
from .temp_model import TemperatureQwen2ForCausalLM
from .templlm_auto import AutoDecoModelForCausalLM